# Generated by Django 3.1.7 on 2021-02-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210220_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
